version: "3.9"  # optional since v1.27.0
services:
  mysql:
    image: mariadb
    volumes:
      - /data/mysql:/var/lib/mysql

  wordpress:
    image: wordpress:php7.3-fpm
    volumes:
      - /data/html:/var/www/html
    environment:
      WP_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WP_DB_NAME: db_name
      WP_DB_USER: user_name
      WP_DB_PASSWORD: user_pass
      WP_TABLE_PREFIX: wp_

nginx:
  image: nginx:debian-buster
  volumes:
    - nginx:/etc/nginx/conf.d
    - /data/html:/var/www/html
    ports:
      - 8080:80

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
networks:
  frontend:
    name: cus_front
    driver: cus_driver_1
volumes: