version:   "3"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: my_nginx:v.1.0.0
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /data/html:/var/www/html
    ports:
      - "127.0.0.1:443:443"
    restart: on-failure
    env_file: 
      - .env
    networks:
      - backend

  mysql:
    container_name: mariaDB
    build: ./requirements/mariadb
    image: my_mariadb:v.1.0.0
    volumes:
      - /data/mysql:/var/lib/mysql
    ports: 
      - "3307:3306"
    restart: on-failure
    env_file: 
      - .env
    networks:
      - backend

  wordpress:
    container_name: wp-php7.3
    build: ./requirements/wordpress
    image: wp-php:v.1.0.0
    volumes:
      - /data/html:/var/www/html
    ports:
      - "9000:9000"
    restart: on-failure
    env_file: 
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge

#volumes:                                       to add correctly later
#  wp:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: /home/plam/data/wp
#  db:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: /home/plam/data/db