version: "3.9"  # optional since v1.27.0
services:
  mysql:
    image: mariadb
    volumes:
      - /data/mysql:/var/lib/mysql

  wordpress:
    image: wordpress:php7.3-fpm
    volumes:
      - /data/html:/var/www/html
    ports:
      - "8000:80"

nginx:
  image: nginx:debian-buster
  volumes:
    - nginx:/etc/nginx/conf.d
    - /data/html:/var/www/html
    ports:
      - 8080:80


  redis:
    image: redis
networks:
  frontend:
    name: cus_front
    driver: cus_driver_1
volumes: