version:   "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /data/html:/var/www/html
    ports:
      - "443:443"
    restart: on-failure
    env_file: 
      - .env
    networks:
      - backend

  mysql:
    image: mariadb
    volumes:
      - /data/mysql:/var/lib/mysql
    ports: 
      - "3306"
    restart: on-failure
    env_file: 
      - .env
    networks:
      - backend

  wordpress:
    image: wordpress:php7.3-fpm
    volumes:
      - /data/html:/var/www/html
    ports:
      - "9000"
    restart: on-failure
    env_file: 
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge